version: "3.7"

services:
  php-apache:
    build: '.'
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./:/var/www/html/
#    environment:
#     - XDEBUG_CONFIG="xdebug.idekey=''"
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    # working_dir: /application
    # volumes:
    #   - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "8082:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 9191:80
